### ISSUE TITLE
What is the principle of automatic fields?

### ISSUE THREAD

**Issue by d4fe** [4lex4/scantailor-advanced#114]
What is the principle of automatic fields? How to understand what result to expect from the use of this function?
(Automatic translation).

**Comment by Piolie** [comment]
The automatic translation is not helping here. What are "automatic fields"? In which step is this option?

**Comment by d4fe** [comment]
![111](https://user-images.githubusercontent.com/63813115/79910528-f19aba00-842f-11ea-852d-d7dfd10e09a1.png)

**Comment by Piolie** [comment]
From the [README](https://github.com/4lex4/scantailor-advanced/blob/master/README.md#auto-margins-improved):

> Auto margins feature allows keep page content on original place. In the Margins step you can choose from Auto, Manual (default) and Original mode. The manual mode is the original one. Auto mode try to decide if it is better to align page top, bottom or center. Original mode keeps page on their vertical original position.

Can't speak for its usefulness since I haven't tried it.

PD: Just for the record, in English the option is called `Auto Margins`.

![AutoMargins](https://user-images.githubusercontent.com/20274082/79917022-21ca6480-8400-11ea-883f-c6fe2a324fc4.png)

**Comment by d4fe** [comment]
In README, I read it, but did not understand anything. In addition, in practice, I also did not understand anything.
