### ISSUE TITLE
Integrate export and multi-page doccument assembly from ST Universal

### ISSUE THREAD

**Issue by mara004** [4lex4/scantailor-advanced#155]
Another feature which the Universal branch added that I would believe to be quite useful or important is being able to export a multi-page document from ScanTailor, rather than needing to use third party software afterwards. In my opinion, it is something that should be integrated into ScanTailor, beacuse it's quicker and easier for users. I wonder whether it's difficult to port this to STA?
I think Universal can only export to (multi-page) tiff, but I would also consider it interesting to be able to export to JPEG / PNG or (multi-page) PDF, too.

**Comment by Piolie** [comment]
This can easily be achieved with any free image batch processing tool, such as ImageMagick. For `PDF` output: `magick convert *.tif out.pdf`. You could also use [tesseract](https://github.com/tesseract-ocr/tesseract) to add an OCR layer.

I think it's not worth the hassle adding it to ST.

**Comment by mara004** [comment]
I agree there are more important problems to work on in STA.
On Linux, I am already using the tiff2pdf command-line utility from libtiff-tools for creating finished documents.
However, it feels awkward to me that additional software is needed, especially on Windows. I don't really want to install a full imagemagick only to assemble the STA output to multi-page PDFs. I think most users would expect to find this functionality in STA directly. It would be a lot easier to use.
The processing workflow I would prefer is without an output directory: Just load the input files, do the editing and when finished, call an export dialog from Tools->Export which lets you choose between different formats (jpeg/png/tiff/pdf) and multi-page/single-page. What I would also like is an option to create a PDF which has a two pages on one layout.

**Comment by Piolie** [comment]
ST could include other related operations (scanning, OCR and document assembly come to mind). However, being still _somewhat_ unstable and essentially a one-man development effort, I think it'd be wiser to concentrate on core functionality —especially that not covered by other free software, and bug fixing.

I agree that the UI could use some improvement, particularly on the documentation side. Maybe this is something us non-programmer users could help with.

For the record: there are official portable distributions of ImageMagick for Windows, so technically it is _not necessary_ to _install_ it.

**Comment by hfiguiere** [comment]
Good arguments for integrating PDF output would be as follow:

- margin could be handled with PDF opcode to position in the page instead of generating a bitmap, including setting the background colour.
- output DPI could be handled by ignoring it and just generate the image in response to the position on the page (like the margins set). This would require to have a page size for the output

But there are things that would need to be done too:
- allow ordering pages (even though this can be done afterwards)

All of this saves so much time by removing the step to generate the images and then going to a different tool to generate the output.
