### ISSUE TITLE
feature_request(split_pages): split by horizontally

### ISSUE THREAD

**Issue by Kristinita** [4lex4/scantailor-advanced#68]
### 1. Summary

It would be nice, if would be possible cut pages by horizontally, not by vertically solely, in `Split Pages` stage.

### 2. Example of expected behavior

Pay attention to blue horizontal line in image top:

![Horizontal line](https://i.imgur.com/J7K1Gi1.png)

It would be nice, if user can remove area above it for further page processing, use `Apply cut` option of `Split Pages` filter.

### 3. Data

+ [**`KiraSuperhero.tif`**](https://drive.google.com/open?id=12yFcGCLOgJ4bBQzJcp6blgI8Vdqi0cI6) — book scan (note: 281 MB)
+ [**`KiraSuperheroSplitPage.ScanTailor`**](https://app.box.com/s/mtwpoqq507us17hys06462a9j7bniyny) — ScanTailor Advanced project for `KiraSuperhero.tif` after run `Split Page` filter
+ [**`KiraSuperheroSelectContent.ScanTailor`**](https://app.box.com/s/nsgifzwxm9kzep1x000hohneirtta7ox) — ScanTailor Advanced project after run `Select Content` filter

#### 4.1. Summary

Less manual working for users, more automatic.

#### 4.2. Details

Problems for scans, that I need to process — black borders in top, left and right of the books pages. They can have different size and positions. Examples:

+ page 24:

![24 borders](https://i.imgur.com/Lehv0JE.png)

+ page 55:

![55 borders](https://i.imgur.com/BF5vcZ2.png)

`Select Content` filter can select this borders. I need to make manual actions, that deselect them. If would be possible cut area above top border, `Select Content` will not select borders; user will have more chances automatically get correct selected area.

### 5. Current behavior

+ page 24:

![24](https://i.imgur.com/ZAUcFEW.png)

+ page 44:

![44](https://i.imgur.com/qn7pXgN.png)

See also pages 10, 12, 14, 32, 64, 66, 70, 80 and so on in `KiraSuperheroSelectContent.ScanTailor`. If would be possible split pages by horizontally, possibly, selected area would be more expected.

### 6. Environment

+ Windows 10 Enterprise LTSB 64-bit EN
+ ScanTailor Advanced 2019.8.16 Early Access

Thanks.

**Comment by 4lex4** [comment]
That's because your source is not from scanner and has already been incorrectly processed with a program.
For correct scans ST automatically excludes outside scanner area on finding content as it is.

Instead of moving split lines try to use https://github.com/4lex4/scantailor-advanced#auto-adjusting-content-area

**Comment by 4lex4** [comment]
Just remembered, use **page area** instead of split lines, as the page area feature is intended to solve problems like yours and this is more effective than that you're suggesting!

Go to the fourth stage:
1. Set page area to manual mode and adjust orange frame
2. Apply page area to all pages via checking `Apply page box` checkbox (you can use apply to every other page to separately set the page area for even and odd pages)
3. Check (and adjust if necessary) the page area for the each page (the page area frame can be moved via `Shift` button pressed just like the content one), trash must be outside the orange frame.
4. Set content detection to Auto, Apply to all the pages **(having unchecked `Apply page box`!)** and then run batch processing. Auto content will be searched only inside the page area.

</br>
Some extra info and a similar situation can be found here (in Russian):  
https://www.forum.ru-board.com/topic.cgi?forum=5&bm=1&topic=32945&start=3024#lt
